@rootApi = http://localhost:8000/api/v1

#====== admin api
### Create new admin
POST {{rootApi}}/admin
Content-Type: application/json

{
"fName": "Prabesh",
"lName": "Bhetwal",
"phone":"0460932918",
"email": "jarvis.pc1@hotmail.com",
"password": "yeahbaby"
}

### Check Verification
GET {{rootApi}}/admin
Content-Type: application/json


#====== admin api
### POST Category
POST {{rootApi}}/category
Content-Type: application/json

{
    "title":"Home Appliances", 
}

### GET Category
GET {{rootApi}}/category
Content-Type: application/json

{
    "title":"Home Appliances", 
}